force-app/main/default/objects/GanttLink__c/GanttLink__c.object-meta.xml
<CustomObject>
    <label>GanttLink</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>GanttLink Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GanttLinks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GanttLink__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GanttLink__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Target</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GanttLink__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GanttTask__c/GanttTask__c.object-meta.xml
<CustomObject>
    <label>GanttTask</label>
    <nameField>
        <label>GanttTask Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GanttTasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GanttTask__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GanttTask__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <label>Parent</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GanttTask__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/GanttData.cls
public with sharing class GanttData {
 
    @RemoteAction
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getTasks() {
       
        // fetching the Records via SOQL
        List<GanttTask__c> Tasks = new List<GanttTask__c>();
        Tasks = [SELECT Id, Name, Start_Date__c, Duration__c, Parent__c FROM GanttTask__c];
 
        List<GanttLink__c> Links = new List<GanttLink__c>();
        Links = [SELECT Id, Type__c, Source__c, Target__c FROM GanttLink__c];
 
        Map<String, Object> result = new Map<String, Object>{'tasks' => Tasks, 'links' => Links };
        return result;
   }
}